### ISSUE TITLE
Feature request: built-in compatiblity with RtDBiomes

### ISSUE THREAD

**Issue by nbusseneau** [shudnal/Seasons#11]
Hey, thanks for Seasons, really love the feature set.

I'm using [RtDBiomes](https://thunderstore.io/c/valheim/p/Soloredis/RtDBiomes/) which adds a lot of extra vegetation and clutter to the base game, making it feel more varied. I saw you already had built-in compatibility with roofs coming from other mods, and was wondering if you'd consider adding built-in compatibility with RtDBiomes as well.

Right now I'm simply adding `_RtD` to `piecePrefabPartialName` in `Materials.json` config to catch RtD prefabs, it mostly works but it's of course not a fine-grained implementation: while it does catch a lot of things, there are some things that are caught that should not, and some others that should be but are not.

(Note: I will probably try my hand at figuring out how to use [RuntimeUnityEditor](https://github.com/ManlyMarco/RuntimeUnityEditor) over the coming weeks to see if I can progressively isolate and make a better config, but for now it's out of my depth 😅)

**Comment by shudnal** [comment]
That's actually a lot of work. You will have to define prefabs, shaders, materials you need to change. Then you have to find what color ranges should be recolored and find colors to merge which won't be looking unnatural to game's colors. Most likely you will also have to need to define some textures pixels ranges to exclude from recoloring.

It can be relatively easy if the mod author made that prefabs with some internal rules on naming and shit. But if it's not then configs will become messy pretty fast.

RuntimeUnityEditor is kinda easy to use. But the whole process is a chore. You can start and see if you really want to do this. I can explain with an example if you won't get it.

I personally don't like RtDBiomes style that much to dedicate so much time to that.
If you manage to make it look pretty enough you can share the resulting configs as a bundle on the nexus. I am not sure I want to built-in this configs because I won't be able to provide compatibility with further RtDBiomes updates.

**Comment by nbusseneau** [comment]
Makes sense, if ongoing support would be a pain then it's better not to have it included. I will have a look into this and will let you know here about progress and if I eventually release a compatibility module.
