### ISSUE TITLE
Season not syncing in coop-multiplayer

### ISSUE THREAD

**Issue by willcp10** [shudnal/Seasons#8]
For some reason, in community multiplayer games, the first season is Spring only for the host, but for other players the starting season is Summer.

Host:
![image](https://github.com/shudnal/Seasons/assets/73892118/df3d48f3-d461-4e6d-9272-cb07da65862c)

Client:
![WhatsApp Image 2024-02-19 at 19 59 08_c66de034](https://github.com/shudnal/Seasons/assets/73892118/38d36fcb-1421-45f1-b2be-483ac795a12d)

**Comment by shudnal** [comment]
Looks like you have lock configuration disabled on server side and season override Summer enabled in client side.

**Comment by willcp10** [comment]
> Looks like you have lock configuration disabled on server side and season override Summer enabled in client side.

Both enabled... This is my Modpack, I upload the configs to assure me and my wife are playing the exact same thing:
https://valheim.thunderstore.io/package/KAW/KAW_Modpack/

**Comment by shudnal** [comment]
You're right. The first season should be Spring. And my only guess is something is wrong with day length, net time (time in seconds since world start) or season override. Current season and day are updated on the server and sent to the clients.

You can try to enable logging in General section and log time in Test section to see if the calculation of current day and season is right. Also when you enable loggin in General you should see the moment the day and season are synced.

It would help if you share the log files from the server and client. With "Logging" enabled and "Log time" disabled. I have no way currently to test it in player-player connection and on dedicated server everything is working just fine. Maybe the logs will help.

**Comment by willcp10** [comment]
Hey, sorry for late response, got a busy day.

Host Log: 
[LogOutput.log](https://github.com/shudnal/Seasons/files/14353995/LogOutput.log)

Client Log:
[LogOutput.log](https://github.com/shudnal/Seasons/files/14354010/LogOutput.log)

If you are up to, we can chat on discord to test player-player stuff, just sent you a friend invite (williamcp10).

**Comment by shudnal** [comment]
Fixed in 1.1.4
